### ISSUE TITLE
virtualenvs are created with a 'local' directory with symlinks pointing at jenkins

### ISSUE THREAD

**Issue by adrianmoisey** [yola/yodeploy#152]
```
root@web3:/srv/myyola/live/virtualenv/local# ls -la
total 20
drwxrwxr-x 2 root root 4096 May  5 17:58 .
drwxrwxr-x 6 root root 4096 May  5 17:58 ..
lrwxrwxrwx 1 root root   81 May  5 18:01 bin -> /var/lib/jenkins/workspace/virtualenv-myyola/JENKINS_SLAVE/precise/virtualenv/bin
lrwxrwxrwx 1 root root   85 May  5 18:01 include -> /var/lib/jenkins/workspace/virtualenv-myyola/JENKINS_SLAVE/precise/virtualenv/include
lrwxrwxrwx 1 root root   81 May  5 18:01 lib -> /var/lib/jenkins/workspace/virtualenv-myyola/JENKINS_SLAVE/precise/virtualenv/lib
```

If a package is built and deployed on the same machine then the symlinks will work (like on int-envs) if not, they will be broken.

This can lead to some confusion: https://yola.slack.com/archives/engineering/p1435142115002574

May be we should make yodeploy look for `local` inside a venv and kill it.

**Comment by jouberthenk** [comment]
You probably know this, but it's worth mentioning since I only discovered it yesterday at https://virtualenv.pypa.io/en/latest/userguide.html

> **Making Environments Relocatable**
Note: this option is somewhat experimental, and there are probably caveats that have not yet been identified.

> **Warning**
The --relocatable option currently has a number of issues, and is not guaranteed to work in all circumstances. It is possible that the option will be deprecated in a future version of virtualenv.

**Comment by stefanor** [comment]
Yep. We have a bunch of hacks to make it actually work.
